templateDir: src/main/mustache/generator-template-overrides/

additionalProperties:
  title: "Hyperledger Cacti - COPM Corda Server"
  groupId:  com.copmCorda
  artifactId: copm-corda
  # TODO: Make sure this automatically gets bumped during releases so that it
  # remains in sync with the package.json version number.
  artifactVersion: 2.0.0-rc.7
  apiSuffix: CopmCorda
  basePackage: com.copmCorda
  packageName: com.copmCorda.server
  apiPackage: com.copmCorda.server.api
  modelPackage: com.copmCorda.server.model

  documentationProvider: none

  enumPropertyNaming: UPPERCASE
  delegatePattern: false
  serviceImplementation: true
  serviceInterface: true

  # TODO:
  # Currently the reactive flavor of the template does not seem to work
  # When specified as true, it produces compiler errors such as:
  # e: /kotlin-spring/src/test/kotlin/org/openapitools/api/ApiApiTest.kt: (11, 32): Unresolved reference: runBlockingTest
  # e: /kotlin-spring/src/test/kotlin/org/openapitools/api/ApiApiTest.kt: (29, 43): Unresolved reference: runBlockingTest
  # e: /kotlin-spring/src/test/kotlin/org/openapitools/api/ApiApiTest.kt: (31, 81): Suspend function 'cordaDeployContractJarsV1' should be called only from a coroutine or another suspend function
  # e: /kotlin-spring/src/test/kotlin/org/openapitools/api/ApiApiTest.kt: (45, 39): Unresolved reference: runBlockingTest
  # e: /kotlin-spring/src/test/kotlin/org/openapitools/api/ApiApiTest.kt: (47, 70): Suspend function 'cordaInvokeContractV1' should be called only from a coroutine or another suspend function
  #
  reactive: false

  # annotationLibrary: none
  # useSwaggerUI: "false"
  # serializableModel: "true"
  # beanValidations: "true"
  useSpringBoot3: "true"
