name: 'Job running CI tools'
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ env.NODEJS_VERSION }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ env.NODEJS_VERSION }}
    - uses: actions/checkout@v4.1.1
    - id: yarn-cache
      name: Restore Yarn Cache
      uses: actions/cache@v4.0.1
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
        path: ./.yarn/
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
    - run: ./tools/ci.sh
      shell: bash
    - if: ${{ (env.JEST_TEST_PATTERN != '') }}
      name: upload junit report
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: 'junit.xml'
        include_passed: true

