# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: CC-BY-4.0

# This is a basic workflow to help you get started with Actions

name: Test Asset Exchange Fabric Local on Docker

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, run_weaver_tests_on_docker_image ]

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_code_changed:
    outputs:
      status: ${{ steps.changes.outputs.weaver_code_changed }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            weaver_code_changed:
              - './weaver/**'
              - '.github/workflows/test_weaver-asset-exchange-fabric.yaml'

  asset-exchange-fabric-local:
    needs: check_code_changed
    if: needs.check_code_changed.outputs.status == 'true'
    # if: ${{ false }}
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1
      - name: run test on docker image
        working-directory: weaver/tests/asset-exchange-fabric-local
        run: docker compose run test
