on:
    # Triggers the workflow on push or pull request events but only for the main branch
    workflow_call:
  
env:
  NODEJS_VERSION: v18.18.2
  RUN_TRIVY_SCAN: true
  RUN_CODE_COVERAGE: true

jobs:
    copm-corda-corda-pledge-and-viewstate:
      continue-on-error: false
      env:
        FULL_BUILD_DISABLED: true
        FREE_UP_GITHUB_RUNNER_DISK_SPACE_DISABLED: false
        JEST_TEST_PATTERN: packages/cacti-plugin-copm-corda/src/test/typescript/integration/test-copm-getverifiedview-corda.test.ts
        JEST_TEST_RUNNER_DISABLED: false
        JEST_TEST_COVERAGE_PATH: ./code-coverage-ts/plc-copm-corda-corda-pledge
        JEST_TEST_CODE_COVERAGE_ENABLED: true
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4.1.1
        - uses: ./.github/actions/copm_test/
        - name: Set up JDK 17
          uses: actions/setup-java@v3.11.0
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Generate github.properties
          run: |
            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.properties

            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.main.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.main.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.main.properties
          working-directory: weaver/tests/network-setups/corda
        - name: Make the corda network
          run: |
            make setup; make pledge-network
            make server&
          working-directory: packages/cacti-plugin-copm-corda
        - name: show the running network
          run: docker container ls
        - run: ./tools/ci.sh
        - name: Upload coverage reports as artifacts
          if: ${{ env.RUN_CODE_COVERAGE == 'true' }}
          uses: actions/upload-artifact@v4.3.3
          with:
            name: coverage-reports-copm-corda-pledge
            path: ./code-coverage-ts/**/

    copm-corda-corda-lock:
      continue-on-error: false
      env:
        FULL_BUILD_DISABLED: true
        FREE_UP_GITHUB_RUNNER_DISK_SPACE_DISABLED: false
        JEST_TEST_PATTERN: packages/cacti-plugin-copm-corda/src/test/typescript/integration/test-copm-lock-claim-corda.test.ts
        JEST_TEST_RUNNER_DISABLED: false
        JEST_TEST_COVERAGE_PATH: ./code-coverage-ts/plc-copm-corda-corda-lock
        JEST_TEST_CODE_COVERAGE_ENABLED: true
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4.1.1
        - uses: ./.github/actions/copm_test/
        - name: Set up JDK 17
          uses: actions/setup-java@v3.11.0
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Generate github.properties
          run: |
            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.properties

            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.main.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.main.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.main.properties
          working-directory: weaver/tests/network-setups/corda
        - name: Make the corda network
          run: |
            make setup; make lock-network
            make server&
          working-directory: packages/cacti-plugin-copm-corda
        - name: show the running network
          run: docker container ls
        - run: ./tools/ci.sh
        - name: Upload coverage reports as artifacts
          if: ${{ env.RUN_CODE_COVERAGE == 'true' }}
          uses: actions/upload-artifact@v4.3.3
          with:
            name: coverage-reports-copm-corda-lock
            path: ./code-coverage-ts/**/

    copm-fabric-fabric-pledge-and-provestate:
        continue-on-error: false
        env:
          CACTI_NPM_PACKAGE_NAME: "@hyperledger-cacti/cacti-plugin-copm-fabric"
          HFC_LOGGING: '{"debug":"console","info":"console","warn": "console","error":"console"}'
          FULL_BUILD_DISABLED: true
          FREE_UP_GITHUB_RUNNER_DISK_SPACE_DISABLED: false
          JEST_TEST_PATTERN: packages/cacti-plugin-copm-fabric/src/test/typescript/integration/test-copm-pledge-claim.test.ts packages/cacti-plugin-copm-fabric/src/test/typescript/integration/test-copm-getverifiedview.test.ts
          JEST_TEST_RUNNER_DISABLED: false
          JEST_TEST_COVERAGE_PATH: ./code-coverage-ts/plc-copm-fabric-fabric-pledge
          JEST_TEST_CODE_COVERAGE_ENABLED: true
          TAPE_TEST_PATTERN: ""
          TAPE_TEST_RUNNER_DISABLED: true
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v4.1.1
          - uses: ./.github/actions/copm_test/
          - name: Make the fabric network
            run: |
              make setup
              make pledge-network --trace
            working-directory: packages/cacti-plugin-copm-fabric
          - name: show the running network
            run: docker container ls
          - run: ./tools/ci.sh
          - name: Upload coverage reports as artifacts
            if: ${{ env.RUN_CODE_COVERAGE == 'true' }}
            uses: actions/upload-artifact@v4.3.3
            with:
              name: coverage-reports-copm-fabric
              path: ./code-coverage-ts/**/

    copm-fabric-fabric-lock:
        continue-on-error: false
        env:
          CACTI_NPM_PACKAGE_NAME: "@hyperledger-cacti/cacti-plugin-copm-fabric"
          HFC_LOGGING: '{"debug":"console","info":"console","warn": "console","error":"console"}'
          FULL_BUILD_DISABLED: true
          FREE_UP_GITHUB_RUNNER_DISK_SPACE_DISABLED: false
          JEST_TEST_PATTERN: packages/cacti-plugin-copm-fabric/src/test/typescript/integration/test-copm-lock-claim.test.ts
          JEST_TEST_RUNNER_DISABLED: false
          JEST_TEST_COVERAGE_PATH: ./code-coverage-ts/plc-copm-fabric-fabric-lock
          JEST_TEST_CODE_COVERAGE_ENABLED: true
          TAPE_TEST_PATTERN: ""
          TAPE_TEST_RUNNER_DISABLED: true
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v4.1.1
          - uses: ./.github/actions/copm_test/
          - name: Make the fabric network
            run: |
              make setup
              make lock-network --trace
            working-directory: packages/cacti-plugin-copm-fabric
          - name: show the running network
            run: docker container ls
          - run: ./tools/ci.sh
          - name: Upload coverage reports as artifacts
            if: ${{ env.RUN_CODE_COVERAGE == 'true' }}
            uses: actions/upload-artifact@v4.3.3
            with:
              name: coverage-reports-copm-fabric-lock
              path: ./code-coverage-ts/**/
