on:
    # Triggers the workflow on push or pull request events but only for the main branch
    workflow_call:
  
env:
  NODEJS_VERSION: v18.18.2
  RUN_TRIVY_SCAN: true
  RUN_CODE_COVERAGE: true

jobs:
    copm-pledge-and-viewstate:
      continue-on-error: false
      env:
        FULL_BUILD_DISABLED: true
        FREE_UP_GITHUB_RUNNER_DISK_SPACE_DISABLED: false
        JEST_TEST_PATTERN: packages/cacti-copm-test-tooling/src/test/typescript/integration/test-copm-getverifiedview.test.ts packages/cacti-copm-test-tooling/src/test/typescript/integration/test-copm-pledge-claim.test.ts
        JEST_TEST_RUNNER_DISABLED: false
        JEST_TEST_CODE_COVERAGE_ENABLED: true
      strategy:
        matrix:
          net1: [corda, fabric]
          net2: [corda, fabric]
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4.1.1
        - uses: ./.github/actions/copm_test/
        - name: Set up JDK 17
          uses: actions/setup-java@v3.11.0
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Generate github.properties
          run: |
            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.properties

            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.main.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.main.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.main.properties
          working-directory: weaver/tests/network-setups/corda
        - name: Make the first network
          run: |
            make setup; make pledge-network
          working-directory: packages/cacti-plugin-copm-${{matrix.net1}}
        - name: Make the second network
          run: |
            make setup; make pledge-network
          working-directory: packages/cacti-plugin-copm-${{matrix.net2}}
          if: ${{ matrix.net1 != matrix.net2 }}
        - name: show the running network
          run: docker container ls
        - run:  JEST_TEST_COVERAGE_PATH=./code-coverage-ts/plc-copm-pledge${{matrix.net1}}-${{matrix.net2}} COPM_NET_1=${{matrix.net1}} COPM_NET_2=${{matrix.net2}}./tools/ci.sh
        - name: Upload coverage reports as artifacts
          if: ${{ env.RUN_CODE_COVERAGE == 'true' }}
          uses: actions/upload-artifact@v4.3.3
          with:
            name: coverage-reports-copm-pledge
            path: ./code-coverage-ts/**/

    copm-lock:
      strategy:
        matrix:
          net1: [corda, fabric]
      continue-on-error: false
      env:
        FULL_BUILD_DISABLED: true
        FREE_UP_GITHUB_RUNNER_DISK_SPACE_DISABLED: false
        JEST_TEST_PATTERN: packages/cacti-copm-test-tooling/src/test/typescript/integration/test-copm-lock-claim.test.ts
        JEST_TEST_RUNNER_DISABLED: false
        JEST_TEST_CODE_COVERAGE_ENABLED: true
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4.1.1
        - uses: ./.github/actions/copm_test/
        - name: Set up JDK 17
          uses: actions/setup-java@v3.11.0
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Generate github.properties
          run: |
            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.properties

            echo "Using ${GITHUB_ACTOR} user."
            echo "username=${GITHUB_ACTOR}" >> github.main.properties
            echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.main.properties
            echo "url=https://maven.pkg.github.com/hyperledger/cacti" >> github.main.properties
          working-directory: weaver/tests/network-setups/corda
        - name: Make the network
          run: |
            make setup; make lock-network
          working-directory: packages/cacti-plugin-copm-${{matrix.net1}}
        - name: show the running network
          run: docker container ls
        - run: COPM_NET_1=${{matrix.net1}} JEST_TEST_COVERAGE_PATH=./code-coverage-ts/copm-lock-${{matrix.net1}}  ./tools/ci.sh
        - name: Upload coverage reports as artifacts
          if: ${{ env.RUN_CODE_COVERAGE == 'true' }}
          uses: actions/upload-artifact@v4.3.3
          with:
            name: coverage-reports-copm-corda-lock
            path: ./code-coverage-ts/**/
